// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0eIBtx6OYPEgfH1unAKxy2ErIJnXlG2M',
    appId: '1:651111705804:web:000523a2445ce884c92669',
    messagingSenderId: '651111705804',
    projectId: 'votingapp-d1e4f',
    authDomain: 'votingapp-d1e4f.firebaseapp.com',
    storageBucket: 'votingapp-d1e4f.appspot.com',
    measurementId: 'G-RR19J708KN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt2GF8bqCriRyjdv1E3boFFb8iRCLRf6w',
    appId: '1:651111705804:android:4b168b0fadd576e8c92669',
    messagingSenderId: '651111705804',
    projectId: 'votingapp-d1e4f',
    storageBucket: 'votingapp-d1e4f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOL3bSa4YCN9VOAEoirEPsfQn50IbEyvw',
    appId: '1:651111705804:ios:8c92bd2a46d12828c92669',
    messagingSenderId: '651111705804',
    projectId: 'votingapp-d1e4f',
    storageBucket: 'votingapp-d1e4f.appspot.com',
    iosBundleId: 'com.example.voteKaro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOL3bSa4YCN9VOAEoirEPsfQn50IbEyvw',
    appId: '1:651111705804:ios:8c92bd2a46d12828c92669',
    messagingSenderId: '651111705804',
    projectId: 'votingapp-d1e4f',
    storageBucket: 'votingapp-d1e4f.appspot.com',
    iosBundleId: 'com.example.voteKaro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0eIBtx6OYPEgfH1unAKxy2ErIJnXlG2M',
    appId: '1:651111705804:web:3a3bdb72d9b55a33c92669',
    messagingSenderId: '651111705804',
    projectId: 'votingapp-d1e4f',
    authDomain: 'votingapp-d1e4f.firebaseapp.com',
    storageBucket: 'votingapp-d1e4f.appspot.com',
    measurementId: 'G-FPJYNCSSS7',
  );
}
